/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
        "../../packages/ui/src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                primary: {
                    50: 'var(--color-primary-50)',
                    100: 'var(--color-primary-100)',
                    200: 'var(--color-primary-200)',
                    300: 'var(--color-primary-300)',
                    400: 'var(--color-primary-400)',
                    500: 'var(--color-primary-500)',
                    600: 'var(--color-primary-600)',
                    700: 'var(--color-primary-700)',
                    800: 'var(--color-primary-800)',
                    900: 'var(--color-primary-900)',
                    950: 'var(--color-primary-950)',
                },
                surface: 'var(--color-surface)',
                'surface-elevated': 'var(--color-surface-elevated)',
                'surface-subtle': 'var(--color-surface-subtle)',
                'surface-hover': 'var(--color-surface-hover)',
                'surface-active': 'var(--color-surface-active)',
                'surface-inset': 'var(--color-surface-inset)',
                'text-primary': 'var(--color-text-primary)',
                'text-secondary': 'var(--color-text-secondary)',
                'text-tertiary': 'var(--color-text-tertiary)',
                'text-muted': 'var(--color-text-muted)',
                'text-inverse': 'var(--color-text-inverse)',
                border: {
                    DEFAULT: 'var(--color-border-default)',
                    subtle: 'var(--color-border-subtle)',
                    hover: 'var(--color-border-hover)',
                },
                success: 'var(--color-success)',
                'success-bg': 'var(--color-success-bg)',
                warning: 'var(--color-warning)',
                'warning-bg': 'var(--color-warning-bg)',
                danger: 'var(--color-danger)',
                'danger-bg': 'var(--color-danger-bg)',
                info: 'var(--color-info)',
                'info-bg': 'var(--color-info-bg)',
                chart: {
                    1: 'var(--color-chart-1)',
                    2: 'var(--color-chart-2)',
                    3: 'var(--color-chart-3)',
                    4: 'var(--color-chart-4)',
                    5: 'var(--color-chart-5)',
                },
            },
            borderRadius: {
                xl: 'var(--radius-xl, 1rem)',
                '2xl': 'var(--radius-2xl, 1.25rem)',
                '3xl': 'var(--radius-3xl, 1.5rem)',
                pill: 'var(--radius-pill, 9999px)',
            },
            fontFamily: {
                sans: ['"Inter"', '"Geist"', 'system-ui', 'sans-serif'],
                mono: ['"JetBrains Mono"', '"Fira Code"', 'monospace'],
            },
            boxShadow: {
                sm: 'var(--shadow-sm)',
                md: 'var(--shadow-md)',
                lg: 'var(--shadow-lg)',
                xl: 'var(--shadow-xl)',
                glow: 'var(--shadow-glow)',
            },
        },
    },
    plugins: [require('tailwindcss-animate')],
};