import { useEffect, useRef, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { ArrowUpRight, Bot, Check, ChevronRight, Loader2, Paperclip, Send, Settings2, Sparkles, Wrench } from 'lucide-react';
import { useAuthStore } from '@/features/auth/stores/authStore';
import { chatApi, type AgentConfig, type ToolSuggestion } from '@/features/chat/api/chatApi';
import './ai-chat.css';

type Message = { id: string; role: 'user' | 'assistant'; content: string; suggestions?: ToolSuggestion[]; mode?: 'agent' | 'catalog' };
const prompts = ['帮我选择 650V SiC MOSFET 的 FoM 分析工具', '双脉冲测试数据应如何开始分析？', '如何规划 HTOL 老化与寿命预测？'];

export default function AIChat() {
  const [searchParams] = useSearchParams(); const navigate = useNavigate(); const user = useAuthStore((state) => state.user);
  const [messages, setMessages] = useState<Message[]>([{ id: 'welcome', role: 'assistant', content: '我是 AI POWER 助手。告诉我你的器件、测试或可靠性问题，我会梳理思路并匹配可直接打开的部门工具。' }]);
  const [input, setInput] = useState(''); const [loading, setLoading] = useState(false); const [configOpen, setConfigOpen] = useState(false); const [config, setConfig] = useState<AgentConfig | null>(null); const [configLoading, setConfigLoading] = useState(false); const [configError, setConfigError] = useState(''); const [apiKey, setApiKey] = useState(''); const bottomRef = useRef<HTMLDivElement>(null); const isPlatformAdmin = Boolean(user?.is_superuser);
  useEffect(() => { bottomRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [messages, loading]);
  useEffect(() => { const prompt = searchParams.get('prompt'); if (prompt) setInput(prompt); }, [searchParams]);
  const openConfig = async () => { if (!isPlatformAdmin) return; setConfigOpen(true); setConfigError(''); setConfigLoading(true); try { setConfig(await chatApi.getConfig()); } catch (error) { setConfigError(error instanceof Error ? error.message : '无法读取 Agent 配置'); } finally { setConfigLoading(false); } };
  const send = async (preset?: string) => { const message = (preset ?? input).trim(); if (!message || loading) return; setMessages((current) => [...current, { id: `u-${Date.now()}`, role: 'user', content: message }]); setInput(''); setLoading(true); try { const result = await chatApi.send(message); setMessages((current) => [...current, { id: `a-${Date.now()}`, role: 'assistant', content: result.reply, suggestions: result.suggestions, mode: result.mode }]); } catch (error) { setMessages((current) => [...current, { id: `e-${Date.now()}`, role: 'assistant', content: `暂时无法连接 AI 助手：${error instanceof Error ? error.message : '请稍后重试'}` }]); } finally { setLoading(false); } };
  const saveConfig = async () => { if (!config) return; setConfigLoading(true); setConfigError(''); try { const saved = await chatApi.saveConfig({ provider: config.provider, model: config.model, base_url: config.base_url, enabled: config.enabled, ...(apiKey ? { api_key: apiKey } : {}) }); setConfig(saved); setApiKey(''); setConfigOpen(false); } catch (error) { setConfigError(error instanceof Error ? error.message : '保存失败'); } finally { setConfigLoading(false); } };
  return <div className="agent-page"><section className="agent-hero"><div><div className="agent-kicker"><Sparkles size={14} /> AI POWER ASSISTANT</div><h1>先把问题说清楚，<em>再打开合适的工具。</em></h1><p>面向功率器件研发的对话入口。AI 只提供建议与工具推荐，任何实际操作由你确认。</p></div><div className="agent-status"><span className="agent-status-dot" /> {config?.enabled && config.key_configured ? 'Agent 已连接' : '工具推荐模式'}{isPlatformAdmin && <button onClick={openConfig}><Settings2 size={15} />配置 Agent</button>}</div></section><section className="agent-workspace"><div className="agent-conversation"><div className="agent-thread">{messages.map((message) => <MessageBubble key={message.id} message={message} onOpenTool={(id) => navigate(`/tools?tool=${encodeURIComponent(id)}`)} />)}{loading && <div className="agent-thinking"><Loader2 size={16} className="animate-spin" /> 正在整理问题与工具目录…</div>}<div ref={bottomRef} /></div><div className="agent-composer"><textarea value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); send(); } }} placeholder="例如：帮我分析双脉冲测试的 Eon / Eoff，并推荐下一步工具" rows={2} /><div className="agent-composer-footer"><span><Paperclip size={14} /> 文件上下文即将支持</span><button className="agent-send" onClick={() => send()} disabled={loading || !input.trim()}>发送 <Send size={15} /></button></div></div></div><aside className="agent-sidebar"><div className="agent-side-label">QUICK START</div><h2>从一个研发问题开始</h2><p>选择常见场景，AI 会给出分析路径与工具卡。</p><div className="agent-prompt-list">{prompts.map((prompt) => <button key={prompt} onClick={() => send(prompt)}><span>{prompt}</span><ChevronRight size={16} /></button>)}</div><div className="agent-side-note"><Wrench size={17} /><div><strong>工具会在对话内出现</strong><p>点击推荐卡即可打开对应工具详情。</p></div></div></aside></section>{configOpen && <AgentConfigPanel config={config} loading={configLoading} error={configError} apiKey={apiKey} onClose={() => setConfigOpen(false)} onChange={setConfig} onKeyChange={setApiKey} onSave={saveConfig} />}</div>;
}

function MessageBubble({ message, onOpenTool }: { message: Message; onOpenTool: (id: string) => void }) { return <article className={`agent-message agent-message--${message.role}`}><div className="agent-avatar">{message.role === 'assistant' ? <Bot size={17} /> : '你'}</div><div className="agent-message-body"><div className="agent-message-name">{message.role === 'assistant' ? 'AI POWER 助手' : '你'} {message.mode === 'agent' && <span>AGENT</span>}</div><p>{message.content}</p>{message.suggestions?.length ? <div className="agent-tool-grid">{message.suggestions.map((tool) => <button key={tool.id} className="agent-tool-chip" onClick={() => onOpenTool(tool.id)}><span className="agent-tool-icon">{tool.icon || '◌'}</span><span><strong>{tool.name}</strong><small>{tool.reason} · {tool.description || '部门工具'}</small></span><ArrowUpRight size={16} /></button>)}</div> : null}</div></article>; }

function AgentConfigPanel({ config, loading, error, apiKey, onClose, onChange, onKeyChange, onSave }: { config: AgentConfig | null; loading: boolean; error: string; apiKey: string; onClose: () => void; onChange: (config: AgentConfig) => void; onKeyChange: (key: string) => void; onSave: () => void }) { return <div className="agent-config-backdrop" role="dialog" aria-modal="true"><section className="agent-config-panel"><div className="agent-config-title"><div><span>PLATFORM ADMIN</span><h2>Agent 连接配置</h2></div><button onClick={onClose}>关闭</button></div>{loading && !config ? <div className="agent-config-loading"><Loader2 className="animate-spin" /> 正在读取配置…</div> : config ? <div className="agent-config-form"><label>模型<input value={config.model} onChange={(event) => onChange({ ...config, model: event.target.value })} placeholder="例如 gpt-4o-mini" /></label><label>兼容接口地址<input value={config.base_url} onChange={(event) => onChange({ ...config, base_url: event.target.value })} placeholder="https://api.openai.com/v1" /></label><label>API Key <small>{config.key_configured ? '已配置；留空可保持不变' : '仅保存于服务端'}</small><input type="password" value={apiKey} onChange={(event) => onKeyChange(event.target.value)} placeholder={config.key_configured ? '••••••••' : '输入 API Key'} /></label><label className="agent-config-switch"><input type="checkbox" checked={config.enabled} onChange={(event) => onChange({ ...config, enabled: event.target.checked })} />启用真实 Agent（未启用时仅提供工具目录推荐）</label>{error && <p className="agent-config-error">{error}</p>}<button className="agent-config-save" onClick={onSave} disabled={loading || (config.enabled && !config.key_configured && !apiKey)}>{loading ? '保存中…' : <><Check size={16} />保存并启用</>}</button></div> : null}</section></div>; }
