import { useState, type CSSProperties } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, Bot, Layers3, ShieldCheck, FolderOpen, ChevronRight } from 'lucide-react';
import { useToolsInfinite } from '@/features/tools/hooks/useTools';
import { useAuthStore } from '@/features/auth/stores/authStore';
import './workspace.css';

import { businessFlows, flowIds, modules, type ModuleId } from '@/features/workflows/catalog';

export default function CapabilityCenter({ moduleId }: { moduleId: ModuleId }) {
  const m = modules[moduleId];
  const navigate = useNavigate();
  const authenticated = useAuthStore(s => s.isAuthenticated);
  const { data, isLoading, isPlaceholderData, error, refetch, hasNextPage, fetchNextPage, isFetchingNextPage } = useToolsInfinite({ group_name: m.group });
  const tools = isPlaceholderData ? [] : data?.pages.flat() ?? [];
  const open = (path: string) => navigate(authenticated ? path : '/login?redirect=' + encodeURIComponent(path));
  const ask = (prompt: string) => open('/chat?context=capability:' + moduleId + '&prompt=' + encodeURIComponent('研发背景：SiC 功率器件。请先确认器件类型及缺失输入，区分已知数据、假设与待验证结论；测试条件和判据以适用产品规格及评审方案为准。\n' + prompt));
  return <div className={'flow-page flow-' + moduleId} style={{ '--flow-accent': m.color } as CSSProperties}>
    <div className="flow-topline"><Link to="/dashboard">工作台</Link><ChevronRight size={13}/><span>{m.title}工作区</span><span className="flow-top-caption">AI × POWER / ENGINEERING</span></div>
    <nav className="flow-nav" aria-label="业务流切换">{businessFlows.map((item, index) => <Link key={item.id} to={item.href} aria-current={moduleId === item.id ? 'page' : undefined}><span>0{index + 1}</span><item.icon size={17}/>{item.title}<ArrowUpRight size={14}/></Link>)}<Link to="/capabilities/projects"><FolderOpen size={17}/>项目管理<ArrowUpRight size={14}/></Link></nav>
    <section className="flow-hero">
      <div className="flow-hero-copy"><div className="flow-eyebrow"><span />{m.en} WORKSPACE</div><h1>{m.headline[0]}<br/><em>{m.headline[1]}</em></h1><p>{m.intro}</p><div className="flow-actions"><button className="flow-primary" onClick={() => ask(m.tasks[0][2])}><Bot size={17}/>与 {m.title} AI 开始<ArrowUpRight size={16}/></button><a className="flow-secondary" href="#flow-tools">探索相关工具<ArrowRight size={16}/></a></div><div className="flow-hero-foot"><span>0{flowIds.indexOf(moduleId) + 1} / 08</span><span>需求到量产 · 全流程协作</span></div></div>
      <div className="flow-visual"><div className="flow-visual-head"><span>{m.label}</span><span>工作示意 · 非实测数据</span></div><WorkspaceVisual key={moduleId} id={moduleId}/><p className="flow-visual-note">{m.note}</p></div>
    </section>
    <section className="flow-path" aria-label="建议工作路径"><span className="flow-path-label">工作路径<small>WORKING PATH</small></span>{m.steps.map((step, i) => <div key={step}><span>0{i + 1}</span><strong>{step}</strong>{i < 3 && <ChevronRight size={15}/>}</div>)}</section>
    <section className="flow-task-section"><div className="flow-section-title"><div><span className="flow-eyebrow">START WITH A QUESTION</span><h2>这次，从哪里开始？</h2></div><p>选择一个场景，带着问题进入 AI 助手。</p></div><div className="flow-tasks">{m.tasks.map(([title, description, prompt], i) => <button key={title} onClick={() => ask(prompt)}><div><span className="flow-task-number">0{i + 1}</span><ArrowUpRight size={20}/></div><h3>{title}</h3><p>{description}</p><span className="flow-task-cta">开始分析<ArrowRight size={14}/></span></button>)}</div></section>
    <section className="flow-bottom">
      <div id="flow-tools" className="flow-tools"><div className="flow-section-title"><div><span className="flow-eyebrow">TOOL LIBRARY</span><h2>{m.title}工具台</h2></div><button className="flow-text-button" onClick={() => open('/tools')}>工具市场<ArrowUpRight size={15}/></button></div><p className="flow-tools-note">来自「{m.group}」的已授权工具</p>
      {isLoading || isPlaceholderData ? <div className="flow-empty">正在加载工具…</div> : error ? <div className="flow-empty"><p>工具暂时加载失败</p><button className="flow-text-button" onClick={() => refetch()}>重新加载</button></div> : tools.length ? <div className="flow-tool-list">{tools.map(tool => <button key={tool.id} onClick={() => open('/tools?tool=' + encodeURIComponent(tool.id))}><span className="flow-tool-icon">{tool.icon || '◇'}</span><span><strong>{tool.name}</strong><small>{tool.description || '查看工具说明并启动'}</small></span><ArrowUpRight size={18}/></button>)}{hasNextPage && <button onClick={() => fetchNextPage()} disabled={isFetchingNextPage}>{isFetchingNextPage ? '加载中…' : '加载更多工具'}</button>}</div> : <div className="flow-empty"><Layers3 size={26}/><h3>为下一项工作，找到合适的工具</h3><p>当前分组暂无可用工具。你可以浏览其他已授权工具，或先与 AI 梳理分析路径。</p><button className="flow-text-button" onClick={() => open('/tools')}>浏览工具市场<ArrowRight size={15}/></button></div>}</div>
      <aside className="flow-handoff"><FolderOpen size={24}/><span className="flow-eyebrow">KEEP THE EVIDENCE</span><h2>让工作有据可循。</h2><p>建议为本次{m.title}工作保留以下资料，方便下一步协作与复盘。</p><ul>{m.deliverables.map((item, i) => <li key={item}><span>0{i + 1}</span>{item}</li>)}</ul><button onClick={() => open('/files')}>前往文件中心<ArrowUpRight size={17}/></button></aside>
    </section>
    <footer className="flow-footer"><span>AI × POWER</span><span>{m.title}工作区 · 工具、资料与工程判断连接在一起</span></footer>
  </div>;
}
function WorkspaceVisual({ id }: { id: ModuleId }) {
  const [selected, setSelected] = useState(0);
  const m = modules[id];
  if ('visualLabels' in m) return <div className="validation-visual"><div className="validation-matrix">{m.visualLabels.map((label, i) => <button key={label} aria-pressed={selected === i} onClick={() => setSelected(i)} className={selected === i ? 'selected' : ''}><span>0{i + 1} / {m.en}</span><strong>{label}</strong></button>)}</div><div className="visual-detail"><span>关注要点</span><strong>{m.visualDetails[selected]}</strong></div></div>;
  if (id === 'epitaxy') return <div className="epi-visual"><div className="epi-stack">{['外延层 / EPILAYER', '缓冲层 / BUFFER', 'SiC 衬底 / SUBSTRATE'].map((name, i) => <button key={name} className={'epi-layer epi-layer-' + i + (selected === i ? ' selected' : '')} onClick={() => setSelected(i)}><span>{name}</span><i/></button>)}</div><div className="visual-detail"><span>关注参数</span><strong>{['厚度 · 掺杂 · 均匀性', '过渡结构 · 缺陷控制', '晶型 · 偏角 · 电阻率与缺陷'][selected]}</strong></div></div>;
  if (id === 'process') return <div className="process-visual"><div className="process-nodes">{['离子注入', '激活退火', '栅介质', '刻蚀', '欧姆接触', '过程量测'].map((name, i) => <button key={name} className={selected === i ? 'selected' : ''} onClick={() => setSelected(i)}><span>FOCUS 0{i + 1}</span><strong>{name}</strong><i/></button>)}</div><div className="visual-detail"><span>关键控制点</span><strong>{['剂量 · 能量 · 注入温度', '激活条件 · 表面保护 · 电阻', '介质质量 · 界面态 · 栅漏电', '关键尺寸 · 深度 · 表面损伤', '接触电阻 · 退火 · 均匀性', '量测口径 · 晶圆坐标 · 批次'][selected]}</strong></div></div>;
  if (id === 'design') return <div className="design-visual"><div className="visual-segment" role="group" aria-label="设计示意切换">{['结构', '仿真', '版图'].map((name, i) => <button key={name} aria-pressed={selected === i} onClick={() => setSelected(i)}>{name}</button>)}</div><svg viewBox="0 0 460 220" role="img" aria-label={['器件截面概念示意', '参数扫描概念示意', '重复单元版图概念示意'][selected]}>{selected === 0 ? <g><rect x="50" y="65" width="360" height="120" fill="#697ac6" opacity=".12"/><rect x="50" y="165" width="360" height="20" fill="#697ac6" opacity=".3"/>{[85,185,285].map(x => <g key={x}><rect x={x} y="40" width="70" height="35" rx="3" fill="#a5b4fc"/><rect x={x+20} y="76" width="30" height="45" rx="3" fill="#697ac6"/><path d={`M${x-10} 85 v55 h90 v-55`} fill="none" stroke="#8997d5" strokeWidth="2"/></g>)}<text x="230" y="210" textAnchor="middle">CELL STRUCTURE / 截面示意</text></g> : selected === 1 ? <g><path d="M50 25v160h360" fill="none" stroke="#8997d5"/>{[0,20,40].map((v,i) => <path key={v} d={`M55 180 Q${190+v} ${180-v} 220 ${100-v} T400 ${40-v/2}`} fill="none" stroke="#697ac6" strokeWidth="3" opacity={1-i*.25}/>)}<text x="230" y="210" textAnchor="middle">PARAMETER SWEEP / 趋势示意</text></g> : <g>{Array.from({length: 24}, (_,i) => <g key={i}><rect x={62+i%8*43} y={24+Math.floor(i/8)*53} width="32" height="42" rx="4" fill="#697ac6" opacity=".16"/><rect x={72+i%8*43} y={30+Math.floor(i/8)*53} width="12" height="30" rx="2" fill="none" stroke="#697ac6"/></g>)}<text x="230" y="210" textAnchor="middle">CELL ARRAY / 排布示意</text></g>}</svg></div>;
  return <div className="validation-visual"><div className="validation-matrix">{['静态电性', '动态开关', '热特性', '安全工作区'].map((name,i) => <button key={name} onClick={() => setSelected(i)} className={selected === i ? 'selected' : ''}><span>{['I–V','Eon / Eoff','Zth','SOA'][i]}</span><strong>{name}</strong><ShieldCheck size={20}/></button>)}</div><div className="visual-detail"><span>需要的证据</span><strong>{['测试条件 · IV / CV 曲线', '测试电路 · 原始开关波形', '功耗条件 · 温升与时间数据', '工作边界 · 脉冲与温度条件'][selected]}</strong></div></div>;
}
